### ISSUE TITLE
Gradle Build failed

### ISSUE THREAD

**Issue by rayobanon** [plast-lab/doop-mirror#2]
After all the setup, I run the command ./doop -h.
This is the error I run into:

FAILURE: Build failed with an exception.

* Where:
Build file '/home/shubham/Desktop/M.TechProject/Doop/yanniss-doop-e9752879fba1/build.gradle' line: 17

* What went wrong:
Error resolving plugin [id: 'net.researchgate.release', version: '2.6.0']
> Could not resolve all dependencies for configuration 'detachedConfiguration1'.
   > Could not determine artifacts for net.researchgate.release:net.researchgate.release.gradle.plugin:2.6.0
      > Could not get resource 'https://plugins.gradle.org/m2/net/researchgate/release/net.researchgate.release.gradle.plugin/2.6.0/net.researchgate.release.gradle.plugin-2.6.0.jar'.
         > Could not HEAD 'https://plugins.gradle.org/m2/net/researchgate/release/net.researchgate.release.gradle.plugin/2.6.0/net.researchgate.release.gradle.plugin-2.6.0.jar'.
            > Remote host closed connection during handshake

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

Anyone who can help me understand the error better?

**Comment by anantoni** [comment]
That's weird, I did not have any issues with the commit you are on. Maybe the resource from where gradle-release-plugin is downloaded was down at the time? Can you please pull and retry too? This doop mirror was a bit outdated after all.

**Comment by anantoni** [comment]
@rayobanon Is this resolved? Can I close it?

**Comment by rayobanon** [comment]
Yes. Actually it was an issue of java version. It runs perfectly fine with java 1.8.
Thanks.
