### ISSUE TITLE
why context for lambda method is Immutable context?

### ISSUE THREAD

**Issue by chennbnbnb** [plast-lab/doop-mirror#3]
related code:
[method-handles.dl](https://github.com/plast-lab/doop-mirror/blob/master/souffle-logic/main/method-handles.dl#L852)
i found lambda method's context always be immutable context, I wonder why? and i think it's better to let lambda method be context-sensitive.

**Comment by gfour** [comment]
Lambdas are very common and this analysis path is always on, thus it tries to avoid performance overheads such as those introduced by context sensitivity. The comment in the clause you link suggests a possible model of context sensitivity for lambda method handles but it was not implemented.
